CREATE TABLE LAWYER ( L_FIRSTNAME CHAR(25) NOT NULL,
					 L_LASTNAME CHAR(25) NOT NULL,
					 L_LAWYERID INTEGER NOT NULL,
					 L_PHONENUMBER INTEGER NOT NULL,
					 L_ADDRESS VARCHAR(50) NOT NULL,
					 L_DOB DATE NOT NULL,
					 L_SSN INTEGER NOT NULL,
					 L_DESCRIPTION VARCHAR(152));
				
CREATE TABLE CLIENT ( CL_FIRSTNAME CHAR(25) NOT NULL,
					 CL_LASTNAME CHAR(25) NOT NULL,
					 CL_CLIENTID INTEGER NOT NULL,
					 CL_PHONENUMBER INTEGER NOT NULL,
					 CL_ADDRESS VARCHAR(50) NOT NULL,
					 CL_DOB DATE NOT NULL,
					 CL_SSN INTEGER NOT NULL,
					 CL_DESCRIPTION VARCHAR(152));
					 
CREATE TABLE CASES (CS_CASENUMBER INTEGER NOT NULL,
					 CS_LAWYERID INTEGER NOT NULL,
				  	 CS_CLIENTID INTEGER NOT NULL,
					 CS_COURTID INTEGER NOT NULL,
					 CS_DATE DATE NOT NULL,
					 CS_DESCRIPTION VARCHAR(152));
	
CREATE TABLE COURT (CR_COURTID INTEGER NOT NULL,
				   CR_COURTNAME CHAR(25) NOT NULL,
				   CR_COURTSTATE CHAR(25) NOT NULL,
				   CR_ZIPCODE INTEGER NOT NULL);